# Generated by Django 4.2.3 on 2023-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_control_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='cow_images/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('cow_type', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('animal_status', models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], max_length=20)),
            ],
        ),
    ]
