# Generated by Django 4.2.3 on 2023-12-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0002_cowinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField()),
                ('cow_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.cowinfo')),
            ],
        ),
    ]
