# Generated by Django 4.2.3 on 2023-12-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0008_cowsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cow_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.cowinfo')),
            ],
        ),
    ]
